(function(){if(!google.nocsixjs&&google.timers&&google.timers.load.t)google.timers.load.t.xjses=(new Date).getTime();})();
(function(){var a={};a.d={};a.a=google.j&&google.j.b;a.e=function(b,c){a.d[b]=c};a.c=function(b){if(google.mc){if(a.a){a.a=false;return a.c("bookmarkInit")}for(var c=0,f=google.mc.length;c<f;c++){var d=b=="dispose"?f-c-1:c;try{var e=a.d[google.mc[d][0]];e&&e[b]&&e[b](google.mc[d][1])}catch(g){google.ml(g,false,{cause:"m"+b,index:d,mid:google.mc[d]&&google.mc[d][0]})}}if(b=="dispose")google.mc=null}};google.med=a.c;google.register=a.e;})();
(function(){var g=true,h=false;google.browser={};google.browser.engine={IE:h,GECKO:h,WEBKIT:h,OPERA:h};google.browser.product={IE:h,FIREFOX:h,SAFARI:h,IPAD:h,CHROME:h,OPERA:h};google.browser.engine.version="";google.browser.product.version="";
google.browser.init=function(a){var b=null,c=null;if(window.opera){google.browser.engine.OPERA=g;google.browser.product.OPERA=g;b=c=/Opera\/(\S+)/}else if(a.indexOf("MSIE")!=-1){google.browser.engine.IE=g;google.browser.product.IE=g;b=c=/MSIE\s+([^\);]+)(\)|;)/}else if(a.indexOf("WebKit")!=-1){google.browser.engine.WEBKIT=g;if(a.indexOf("Chrome")!=-1){google.browser.product.CHROME=g;c=/Chrome\/(\S+)/}else if(a.indexOf("iPad")!=-1){google.browser.product.IPAD=g;c=/Version\/(\S+)/}else if(a.indexOf("Safari")!=
-1){google.browser.product.SAFARI=g;c=/Version\/(\S+)/}b=/WebKit\/(\S+)/}else if(a.indexOf("Gecko")!=-1){google.browser.engine.GECKO=g;if(a.indexOf("Firefox")!=-1){google.browser.product.FIREFOX=g;c=/Firefox\/(\S+)/}b=/rv\:([^\);]+)(\)|;)/}if(b){b=b.exec(a);google.browser.engine.version=b?b[1]:""}if(c){b=c.exec(a);google.browser.product.version=b?b[1]:""}};google.browser.init(window.navigator.userAgent);
google.browser.compareVersions=function(a,b){function c(p,q){if(p<q)return-1;else if(p>q)return 1;return 0}for(var d=0,e=a.replace(/^\s+|\s+$/g,"").split("."),f=b.replace(/^\s+|\s+$/g,"").split("."),i=Math.max(e.length,f.length),j=0;d==0&&j<i;j++){var k=e[j]||"",o=f[j]||"",r=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var m=r.exec(k)||["","",""],n=s.exec(o)||["","",""];if(m[0].length==0&&n[0].length==0)break;d=m[1].length==0?0:parseInt(m[1],10);var t=n[1].length==0?0:parseInt(n[1],
10);d=c(d,t)||c(m[2].length==0,n[2].length==0)||c(m[2],n[2])}while(d==0)}return d};google.browser.isEngineVersion=function(a){return google.browser.compareVersions(google.browser.engine.version,a)>=0};google.browser.isProductVersion=function(a){return google.browser.compareVersions(google.browser.product.version,a)>=0};google.style=google.style||{};google.style.hasClass=function(a,b){if(!a||!b)return h;return RegExp("(^|\\s)"+b+"($|\\s)").test(a.className)};google.style.addClass=function(a,b){if(a&&b&&!google.style.hasClass(a,b)){var c=a.className==""?[]:a.className.split(/\s/);c.push(b);a.className=c.join(" ")}};google.style.removeClass=function(a,b){if(google.style.hasClass(a,b)){for(var c=a.className.split(/\s/),d=c.length-1;d>=0;d--)c[d]==b&&c.splice(d,1);a.className=c.join(" ")}};google.dom={};google.dom.g=/^(\w+)?(?:\.(.+))?$/;google.dom.h=/^#([\w-]+)$/;google.dom.append=function(a){return(document.getElementById("xjsc")||document.body).appendChild(a)};google.dom.create=function(a,b){var c=a.match(google.dom.g),d=document.createElement(c[1]);if(c[2])d.className=c[2];if(b)d.innerHTML=b;return d};
google.dom.get=function(a,b,c){var d;if(d=a.match(google.dom.h)){a=document.getElementById(d[1]);return c?a?[a]:[]:a}else{d=a.match(google.dom.g);a=d[2]&&RegExp("\\b"+d[2]);b=(b||document).getElementsByTagName(d[1]||"*");if(a){d=b;b=[];for(var e=0,f;f=d[e++];)a.test(f.className)&&b.push(f)}}return b.length>1||c?b:b[0]};google.dom.insert=function(a,b,c){return b.parentNode.insertBefore(a,c?b.nextSibling:b)};google.dom.remove=function(a){return a&&a.parentNode&&a.parentNode.removeChild(a)};
google.dom.set=function(a){for(var b=1;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1],e=a.style;if(e&&c in e)e[c]=d;else if(c in a)a[c]=d;else if(google.browser.engine.IE&&e&&c=="opacity"){a.zoom=1;e.filter=(e.filter||"").replace(/alpha\([^)]*\)/,"")+"alpha(opacity="+d*100+")"}}return a};google.listen=function(a,b,c){a.addEventListener?a.addEventListener(b,c,h):a.attachEvent("on"+b,c)};google.unlisten=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,h):a.detachEvent("on"+b,c)};google.msg={};google.msg.b={};google.msg.listen=function(){for(var a=0;a<arguments.length-1;a+=2){var b=arguments[a];google.msg.b[b]||(google.msg.b[b]=[]);google.msg.b[b].push(arguments[a+1])}};google.msg.unlisten=function(){for(var a=0;a<arguments.length-1;a+=2){var b=arguments[a];if(b=google.msg.b[b])for(var c=arguments[a+1],d=0;d<b.length;++d)if(b[d]==c){b.splice(d,1);break}}};
google.msg.send=function(a,b,c,d){var e=c===undefined?g:c,f=c===h;c=b&&b[0]===c;if(a in google.msg.b){if(d===undefined)d=h;var i;i=typeof d=="function"?d:function(o){return o===d};for(var j=0,k;k=google.msg.b[a][j++];){k=k.apply(this,b||[]);if(f)e=e||k;else{if(c)b[0]=k;e=k;if(i(e))break}}}return e};google.nav=function(a,b){google.nav.e(a,b)};google.nav.a=function(){return window.location};google.nav.j=location.protocol+"//"+location.host;google.nav.go=function(a,b){google.nav.e(a,b)};
google.nav.e=function(a,b){try{if(RegExp("^("+google.nav.j+")?/(url|aclk)\\?.*&rct=j(&|$)").test(a))if(b){google.r=1;b.location.replace(a)}else{if(!google.nav.c){google.nav.c=document.createElement("iframe");google.nav.c.style.display="none";google.dom.append(google.nav.c)}google.r=1;google.nav.c.src=a}else google.nav.a().href=a}catch(c){google.nav.a().href=a}};
google.nav.search=function(a){var b=google.nav.a().search.match(/[?&][\w\.\-~]+=([^&]*)/g),c={};if(b)for(var d=0,e;e=b[d++];){var f=e.match(/([\w\.\-~]+?)=(.*)/);e=f[1];f=f[2];c[e]=f}for(e in a)if(a.hasOwnProperty(e))c[e]=a[e];a=["/search?"];b=g;for(e in c)if(c.hasOwnProperty(e)){a.push((b?"":"&")+e+"="+c[e]);b=h}google.nav.go(a.join(""))};google.nav.getLocation=function(){return google.nav.a().pathname+google.nav.a().search};
google.nav.getLocationHash=function(){var a=google.nav.a();return a.hash?a.href.substr(a.href.indexOf("#")):""};google.nav.getParam=function(a){var b=google.nav.getLocationHash().match("[#?&]"+a+"=([^&]*)");if(b)return b[1];if(b=google.nav.a().search.match("[?&]"+a+"=([^&]*)"))return b[1];return null};google.nav.getQuery=function(){return google.nav.getParam("q")};google.util={};var l=["&","&amp;","<","&lt;",">","&gt;",'"',"&quot;","'","&#39;","{","&#123;"];google.util.escape=function(a){for(var b=0;b<l.length;b+=2)a=a.replace(RegExp(l[b],"g"),l[b+1]);return a};google.util.unescape=function(a){for(var b=0;b<l.length;b+=2)a=a.replace(RegExp(l[b+1],"g"),l[b]);return a};google.util.eventTarget=function(a){return google.browser.engine.IE?window.event.srcElement:a.target};
google.util.stopPropagation=function(a){if(a)a.stopPropagation&&a.stopPropagation();else window.event.cancelBubble=g};google.srp={};google.srp.d=function(a,b,c){var d=RegExp("([?&])"+b+"=.*?(&|$)");a=a.replace(/^(.*)(#|$)/,function(e,f){return f});if(!a.match(d)&&c!="")return a+"&"+b+"="+c;return a.replace(d,function(e,f,i){return c?f+b+"="+c+i:i?f:""})};google.srp.isSerpLink=function(a){return/(search|images)/.test(a.href)};google.srp.isSerpForm=function(a){return/\/search$/.test(a.action)};
google.srp.updateLinksWithParam=function(a,b,c,d){var e=document.getElementsByTagName("A");google.base_href=google.srp.d(google.base_href,a,b);for(var f=0,i;i=e[f++];)if(c(i)){var j=google.browser.engine.IE?i.innerHTML:undefined;i.href=google.srp.d(i.href,a,b);if(j!=undefined)i.innerHTML=j}for(f=0;c=document.forms[f++];)if(d(c)){for(i=e=0;j=c.elements[i++];)if(j.name==a){e=1;if(b!="")j.value=b;else j.parentNode.removeChild(j)}if(!e&&b!=""){e=document.createElement("input");e.type="hidden";e.value=
b;e.name=a;c.appendChild(e)}}};google.srp.qs=function(a){if(a=google.util.eventTarget(a)){for(;!google.style.hasClass(a,"qs");){a=a.parentNode;if(!a||a==document.body)return}var b=document.getElementsByName("q"),c=b&&b[0];b=document.getElementById("tsf-oq");if(c&&b&&window.encodeURIComponent){c=c.value;b=google.browser.engine.GECKO?b.textContent:b.innerText;if(c&&c!=b){b=google.srp.d(a.href,"q",encodeURIComponent(c));a.href=google.srp.d(b,"prmd","")}}}};google.style=google.style||{};google.style.i=0;
google.style.getComputedStyle=function(a,b,c){var d=c?"":0;var e=document.defaultView&&document.defaultView.getComputedStyle(a,"");try{d=e.getPropertyValue(b);d=c?d:parseInt(d,10)}catch(f){}return d};google.style.getHeight=function(a){var b=google.style.getComputedStyle(a,"height");return isNaN(b)?0:b};
google.style.getWidth=function(a){var b=google.style.getComputedStyle(a,"width");return isNaN(b)?0:b};
google.style.getPageOffsetTop=function(a){return a.offsetTop+(a.offsetParent?google.style.getPageOffsetTop(a.offsetParent):0)};google.style.getPageOffsetLeft=function(a){return a.offsetLeft+(a.offsetParent?google.style.getPageOffsetLeft(a.offsetParent):0)};google.style.getPageOffsetStart=function(a){return google.style.getPageOffsetLeft(a)+google.style.i?google.style.getWidth(a):0};google.style.getColor=function(a){return google.style.getComputedStyle(a,"color",g)};google.xhr=function(){var a=null;if(window.XMLHttpRequest)try{a=new XMLHttpRequest}catch(b){}if(!a)for(var c=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],d=0,e;e=c[d++];)try{a=new ActiveXObject(e);break}catch(f){}return a};google.isOpera=h;google.isIE=h;google.isSafari=h;
google.getHeight=function(a){return google.style.getHeight(a)};google.getWidth=function(a){return google.style.getWidth(a)};google.getComputedStyle=function(a,b,c){return google.style.getComputedStyle(a,b,c)};google.getPageOffsetTop=function(a){return google.style.getPageOffsetTop(a)};google.getPageOffsetLeft=function(a){return google.style.getPageOffsetLeft(a)};google.getPageOffsetStart=function(a){return google.style.getPageOffsetStart(a)};
google.hasClass=function(a,b){return google.style.hasClass(a,b)};google.getColor=function(a){return google.style.getColor(a)};google.append=function(a){return google.dom.append(a)};google.rhs=function(){};google.eventTarget=function(a){return a.target;};google.bind=function(a,b,c){google.listen(a,b,c)};
google.unbind=function(a,b,c){google.unlisten(a,b,c)};google.getURIPath=function(){return google.nav.getLocation()};})();
(function(){var c=window,f=Object,h=google,i="push",j="length",k="propertyIsEnumerable",l="prototype",m="call";
function n(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof f)&&f[l].toString[m](a)=="[object Array]"||typeof a[j]=="number"&&typeof a.splice!="undefined"&&typeof a[k]!="undefined"&&!a[k]("splice"))return"array";if(!(a instanceof f)&&(f[l].toString[m](a)=="[object Function]"||typeof a[m]!="undefined"&&typeof a[k]!="undefined"&&!a[k]("call")))return"function"}else return"null";else if(b=="function"&&typeof a[m]=="undefined")return"object";return b}
function o(a){return(new p).serialize(a)}function p(){}p[l].serialize=function(a){var b=[];this.a(a,b);return b.join("")};p[l].a=function(a,b){switch(typeof a){case "string":this.b(a,b);break;case "number":this.d(a,b);break;case "boolean":b[i](a);break;case "undefined":b[i]("null");break;case "object":if(a==null){b[i]("null");break}if(n(a)=="array"){this.c(a,b);break}this.e(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var q={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},r=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;p[l].b=function(a,b){b[i]('"',a.replace(r,function(g){if(g in q)return q[g];var d=g.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return q[g]=e+d.toString(16)}),'"')};p[l].d=function(a,b){b[i](isFinite(a)&&!isNaN(a)?a:"null")};
p[l].c=function(a,b){var g=a[j];b[i]("[");for(var d="",e=0;e<g;e++){b[i](d);this.a(a[e],b);d=","}b[i]("]")};p[l].e=function(a,b){b[i]("{");var g="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b[i](g);this.b(d,b);b[i](":");this.a(e,b);g=","}}b[i]("}")};c.google.stringify=o;if(c.JSON&&c.JSON.stringify&&navigator.userAgent.indexOf("Chrome")==-1)c.google.stringify=c.JSON.stringify;h.History={};var s=[],t="/";h.History.client=function(a){s[i](a);return s[j]-1};var u,v;function w(){var a=u.value;v=a?eval("("+a+")"):{}}function x(a,b){w();v[t]||(v[t]={});v[t][a]=b;u.value=h.stringify(v)}var y=[];function z(){for(var a=0,b;b=y[a++];)b();y=[]}h.History.addPostInitCallback=function(a){y[i](a)};h.History.save=function(a,b){u&&x(a,b)};h.History.initialize=function(a){t=a;v=null;if(u=document.getElementById("hcache")){w();for(a=0;a<s[j];++a)v&&v[t]&&v[t][a]&&s[a][m](null,v[t][a]);z()}};})();
(function(){var a,b;google.rhs=function(){if(!google.drhs)if(document.getElementById("mbEnd")&&(a||b)){var d=google.getHeight(document.getElementById("rhsline")),c=a?google.getHeight(a):0;if(b)c+=google.getHeight(b)+18;document.getElementById("rhspad").style.height=c>d?Math.min(9999,c-d)+"px":google.isIE?"":0}};function e(){a=document.getElementById("tads");b=document.getElementById("3po");google.rhs()}e();google.bind(window,"resize",google.rhs);google.rein.push(e);})();
(function(){var e=0,f=[];google.fx={};google.fx.linear=function(a){return a};google.fx.easeOut=function(a){return 1-Math.pow(1-a,3)};google.fx.easeInAndOut=function(a){return(3-2*a)*a*a};google.fx.animate=function(a,d,g){for(var b=0,c;c=d[b++];){c[5]=c[5]==null?"px":c[5];c[4]=c[4]||google.fx.linear;google.dom.set(c[0],c[1],c[2]+c[5])}f.push({b:a,a:g,d:google.time(),c:d});e=e||window.setInterval(h,15)};function h(){for(var a=0,d;d=f[a++];)i(d)||f.splice(--a,1);if(!f.length){window.clearInterval(e);e=0}}
function i(a){var d=google.time()-a.d;if(d>=a.b){for(var g=0,b;b=a.c[g++];)google.dom.set(b[0],b[1],b[3]+b[5]);a.a&&a.a();return 0}else{for(g=0;b=a.c[g++];){var c=b[2]+(b[3]-b[2])*b[4](d/a.b);if(b[5]=="px")c=Math.round(c);google.dom.set(b[0],b[1],c+b[5])}return 1}}google.fx.wrap=function(a){var d=document.createElement("div");a.parentNode.replaceChild(d,a);d.appendChild(a);return d};google.fx.unwrap=function(a){a.parentNode.parentNode.replaceChild(a,a.parentNode)};
google.dstr.push(function(){window.clearInterval(e);e=0;f=[]});})();
(function(){google.event=google.event||{};google.event.back={};var d=[],f=[],g={persisted:false};google.event.back.saveHistory=function(){google.History.save(i,g)};var j=google.event.back.saveHistory;function k(){for(var b=[],c=0,a=d.length;c<a;c++){var e=d[c](g[f[c]]);if(e){b.length>0&&b.push(",");b.push(e)}}b.push("&ei=",google.kEI);window.google.log("backbutton",b.join(""))}
function l(b,c){return function(a){a=a||window.event;for(a=a.target||a.srcElement;a.parentNode&&a.tagName!="A";)a=a.parentNode;b(a,c?g[c]:null);c&&j()}}function m(b,c,a){for(var e=document.getElementsByTagName("a"),o=0,h;h=e[o++];)b(h)&&google.bind(h,"click",l(c,a))}function n(){if(!g.persisted){g.persisted=true;j();if(window.addEventListener){window.addEventListener("pageshow",p,false);q=false}}}var r=google.j&&google.j.en,q;function p(b){if((b.persisted||q)&&!r)k();q=true}
var i=google.History.client(function(b){g=b;g.persisted&&k()});google.event.back.register=function(b,c,a,e){if(e)g[e]={};m(b,c,e);d.push(a);f.push(e)};google.event.back.init=function(){g={persisted:false};google.History.addPostInitCallback(n)};function s(){d.length=0;f.length=0}google.dstr&&google.dstr.push(s);})();
(function(){var h=true,j=null,k=false,l=window.google.ac={},aa=k,ba,n,o,da,p,ea,fa,ga,ha,ia,ja,ka,la,ma,q,r,s,na,v="",oa=j,w=j,x=j,y=-1,z,C,D,E,F,pa,G,H,K,qa,ra,sa,L,ta,ua={},va,N=0,O=0,wa=k,P=j,Q=0,xa,ya;var R;var W;function Ca(a){return(a=a&&a.match(/\D+$/))?a[0]:j}var Da="hp",Ea="serp",Fa="img",Ga={0:Da,1:Ea,2:Fa},X;function Ha(a){return(document.getElementById("main")||document.getElementById("xjsc")||document.body).appendChild(a)}
function Ia(){Ja();Y();if(z){K.value=qa.value=ra.value=L.value=sa.value="";window.clearTimeout(oa);v=ya=va="";oa=w=x=j;y=-1;X=N=O=Q=0;ua={};R=0;}}function Ka(a,b){X=0;if(a=="i")X=2;else if(b&&b!="")X=1}
function La(a,b,c,d,e,g){Ka(c,d);Ma();g&&Na(g);Oa();z=a;C=b;s=na=r=C.value;n=k;o="";if(!b.init){xa=document.getElementsByTagName("head")[0];google.bind(z,"submit",Pa);C.setAttribute("autocomplete","off");google.bind(C,"blur",Y);C.onkeypress=Qa;google.bind(C,"keyup",Ra);K=Z("aq","f");qa=Z("aqi","");ra=Z("aql","");L=Z("oq",s);sa=Z("gs_rfai","");G=F=document.createElement("table");F.cellSpacing=F.cellPadding="0";H=pa=F.style;F.className="gac_m";if(q){G=D=document.createElement("div");D.className="gac_od";H=D.style;Ha(D);if(X==1){a=document.createElement("div");a.className="gac_wd";D.appendChild(a)}E=document.createElement("div");E.cellSpacing=
D.cellPadding="0";E.className="gac_id";D.appendChild(E);E.appendChild(F)}else z.appendChild(F);p=document.createElement("div")}b.init=h;Y();Sa();if(!aa){Ta();aa=h}b=Ga[X];b="&client="+b;c=c?"&ds="+c:"";a=e?"&tok="+encodeURIComponent(e):"";d=["?hl=",google.kHL,b,Ua(),c,(d?"&pq="+encodeURIComponent(d):""),a].join("");va="/complete/search"+d;ya="/complete/deleteitems"+d;R=Va(C);google.bind(window,"pageshow",function(f){if(f.persisted){K.value="f";
L.value=C.value}});Xa();ma="https:"==document.location.protocol;e=ka||e&&e.length||ma;la=["http",e?"s":"","://"].join("");(new Image).src=la+"clients1.google.es/generate_204";}
function Ta(){function a(d,e){b.push(d,"{",e,"}")}var b=[];if(q){var c="background:white;margin:0;z-index:99;";a(".gac_od",c+"border-top:0;border-left:0;border-right:1px solid #e7e7e7;border-bottom:1px solid #e7e7e7;padding:0!important;position:absolute;zoom:1");a(".gac_id",c+"border-top:1px solid #a2bff0;border-left:1px solid #a2bff0;border-right:1px solid #558be3;border-bottom:1px solid #558be3;display:block");a(".gac_m",c+"border:0;cursor:default;display:block;font-size:17px;line-height:117%;padding:0;position:relative;zoom:1");
if(!document.body.dir||document.body.dir=="ltr")a(".gac_wd","background:#999;height:1px;position:absolute;right:-1px;top:0;width:1px;z-index:100")}else a(".gac_m","background:white;border:1px solid #666;cursor:default;font-size:17px;line-height:117%;margin:0;position:absolute;z-index:99");a(".gac_m td","line-height:22px");a(".gac_n","padding-top:1px;padding-bottom:1px");a(".gac_b td.gac_c","background:#d5e2ff");
a(".gac_b","background:#d5e2ff");a(".gac_a td.gac_f","background:#fff8dd");a(".gac_p","padding:1px 4px 2px 3px");a(".gac_u","padding:0 0 1px 0;line-height:117%;text-align:left");a(".gac_t","width:100%;text-align:left;font-size:17px");a(".gac_za","position:absolute;bottom:0;right:0;text-align:right;font-size:12px;padding-right:5px");a(".gac_bt","width:"+(C.offsetWidth-2)+"px;text-align:center;padding:8px 0 7px;position:relative");a(".gac_sb","font-size:15px;height:28px;margin:0.2em");a(".gac_z","white-space:nowrap;color:#c00");a(".gac_s","height:3px;font-size:1px");c=q?7:3;c="white-space:nowrap;overflow:hidden;text-align:left;padding-left:"+c+"px;padding-right:3px";a(".gac_c",c);a(".gac_e","text-align:right;padding:0 3px");
a(".gac_d","font-size:11px");a(".gac_h","color:green");a(".gac_j","display:block");a(".gac_l","line-height:18px");a(".gac_x","display:block;line-height:16px");a(".gac_y","font-size:13px");a(".gac_i","color:#666");a(".gac_w img","width:40px;height:40px");a(".gac_w","width:1px");a(".gac_r","color:red");a(".gac_v","padding-bottom:5px");c=document.createElement("style");
c.setAttribute("type","text/css");xa.appendChild(c);b=b.join("");c.appendChild(document.createTextNode(b));}
function Sa(){if(G){var a=Ya(C);H.left=a.D+"px";a=a.G+C.offsetHeight-1;q&&X==1&&a++;H.top=a+"px";a=C.offsetWidth;if(q)H.minWidth=a+"px";else H.width=a+"px";if(w){var b=$(0);if(b&&a-12>=0)b.firstChild.style.width=a-12+"px"}}}function Ya(a){for(var b=0,c=0;a;){b+=a.offsetTop;c+=a.offsetLeft;a=a.offsetParent}return{G:b,D:c}}
function Z(a,b){var c=document.createElement("input");c.type="hidden";c.name=a;c.value=b;return z.appendChild(c)}function Qa(a){var b=a.keyCode;if(b==27&&Za()){Y();$a(s);a.cancelBubble=h;return a.returnValue=k}if(b==13){ab(k);a.cancelBubble=h;return a.returnValue=k}if(b==38||b==40){O++;O%3==1&&Wa(b);return k}}
function ab(a){if(!a&&ta){z.removeChild(ta);ta=j}if(x&&y!=-1&&wa&&!(a&&x.C))x.onclick(j);else if(C.value=="")Y();else{if(a)ta=Z("btnI","1");bb()}}function bb(){Pa();z.onsubmit&&z.onsubmit()==k||z.submit()}function Ra(a){a=a.keyCode;if(!O)Wa(a);O=0;}
function Wa(a){if(C.value!=r){s=C.value;R=Va(C);L.value=s}if(a==40||a==38){cb(a==40);wa=Za()}Sa();if(v!=s&&!P)P=window.setTimeout(Y,500);r=C.value}
function db(){wa=k;if(!Q){if(x)x.className="gac_a";x=this;for(var a=0,b;b=$(a);a++)b==x&&(y=a);x.className="gac_b"}}function eb(a,b){return function(c){fb(hb(a),b);ib(c);return k}}function hb(a){return[a,"&aq=",x.q,"&oq=",L.value,jb("aqi",qa),jb("aql",ra),jb("gs_rfai",sa)].join("")}
function jb(a,b){if(b&&b.value.length&&a.length)return["&",a,"=",b.value].join("");return""}function fb(a,b){var c=window.frames.wgjf;if(c&&!b){google.r=1;c.location.replace(a)}else window.location=a}
function kb(){$a(this.k);bb();}
function cb(a){if(!(s!=v||!w||!w.length))if(Za()){if(x)x.className="gac_a";for(var b=w.length,c=(y+1+(a?1:b))%(b+1)-1;c!=-1&&$(c).w;)c=(c+1+(a?1:b))%(b+1)-1;y=c;if(y==-1)lb();else{x=$(c);x.className="gac_b";$a(x.k);K.value=x.q}}else mb()}function lb(){C.focus();$a(s);x=j;K.value="f"}function Y(){if(P){window.clearTimeout(P);P=j}H&&(H.visibility="hidden");}
function mb(){H&&(H.visibility="visible");Sa();Q=1}function Za(){return!!H&&H.visibility=="visible"}function Ja(){if(F){F.innerHTML="";}}
function nb(a,b,c){a.onclick=b?eb(b,c):kb;a.C=!b;a.onmousedown=ob;a.onmouseover=db;a.onmousemove=function(){if(Q){Q=0;db.call(this)}}}function pb(a,b){ib(a);for(var c=0,d;d=$(c++);)if(d.q==b){qb(ya,"delq",d.k,rb);break}return k}function rb(a){for(var b=0,c;c=$(b++);)if(Ca(c.q)=="p"&&c.k==a[0]){c.w=1;c.onclick=c.onmouseover=j;if(c==x){c.className="gac_a";y=-1;lb()}c.z.className="gac_c gac_i fl";c.z.innerHTML="Esta búsqueda se ha eliminado de tu \x3ca href\x3d\x22/history\x22\x3ehistorial web\x3c/a\x3e."}}
function sb(a){function b(Db,gb){var ca=gb?Ca(gb[2]):j;ca=Db+(ca?"-"+ca:"");if(ca!=e){if(g)d+=e+g;g=0;e=ca}g++}var c=a[0];N>0&&N--;if(!(!F||c!=s)){if(P){window.clearTimeout(P);P=j}v=a[0];Ja();var d="",e,g=0,f=a[1],i=f.length-1;c=k;for(var m=0,t,u,I,J,A,M,B;m<=i;m++)if(B=f[m]){t=B[1];if(A=ua[t]){A.A&&A.A(m,i)&&tb();u=B[2];I=B[3];J=A.m?A.m(B,I):j;M=F.insertRow(-1);nb(M,J,A.B);M.q=u;M.className="gac_a";J=M.z=document.createElement("td");
J.className="gac_c";A.g(J,u,B,I);u=A.v;M.k=u?u(B,I,v):B[0];M.appendChild(J);b(A.b,B);m<i&&A.F&&tb();if(!c&&t!=30&&!ub(B))c=h}}ra.value=a[3]||"";sa.value=a[4]||"";if((w=F.rows)&&w.length>0){n=w.length<10;if(X==0)wb();else if(X==1&&ja){f=tb();i=
f.style;i.textAlign="right";i.fontSize="12px";i.paddingRight="5px";f.innerHTML=xb()}mb()}else{Y();n=h}if(c)n=k;if(n&&!o){o=v;da=a}b("");qa.value=d;y=-1}}
function yb(a){function b(I,J){g.push({t:e.join(""),s:I,e:J})}function c(I){t.push("<b>",I,"</b> ")}a=zb(a);var d=s.replace(/^\s+|\s+$/g,"").replace(/\s\s+/g," ");if(!a.indexOf(d))return[d,"<b>",a.substr(d.length),"</b>"].join("");var e=[],g=[],f=a.length-1;d=0;for(var i=-1,m;m=a.charAt(d);++d)if(m==" "||m=="\t"){if(e.length){b(i,d+1);e=[];i=-1}}else{e.push(m);if(i==-1)i=d;else d==f&&b(i,d+1)}f=Ab(g);if(!f.length)return["<b>",a,"</b>"].join("");var t=[];for(d=i=0;m=f[d];++d){var u=g[m.s];(u=u.s)&&
c(a.substring(i,u-1));i=g[m.e].e;t.push(a.substring(u,i))}i<a.length&&c(a.substring(i));return t.join("")}function Ab(a){function b(m,t){f.push({s:m,e:t})}for(var c=s.split(/\s+/),d={},e=0,g;g=c[e++];)d[g]=1;c=-1;var f=[],i=a.length-1;for(e=0;g=a[e];++e)if(d[g.t]){g=c==-1;if(e==i)b(g?e:c,e);else if(g)c=e}else if(c>-1){b(c,e-1);c=-1}return f}
function $(a){b=w.item(a);return b}
function Bb(a){var b=a?"Voy a tener suerte":"Buscar con Google",c="gac_sb",d="",e="";if(q){c="lsb";d="<span class=ds><span class=lsbb>";e="</span></span>"}return[d,'<input type=button value="',b,'" class=',c,' onclick="google.ac.rd(',a,')">',e].join("")}
function wb(){var a=F.insertRow(-1);a.w=1;a.onmousedown=ob;var b="";if(ja)b="<div class=gac_za>"+xb()+"</div>";a=a.insertCell(0);a.innerHTML=['<div style="position:relative"><div class=gac_bt>',Bb(k),Bb(h),"</div>",b,"</div>"].join("")}function xb(){return'<a href="http://www.google.com/support/websearch/bin/answer.py?hl=fr&answer=106230">En savoir plus</a>'}function zb(a){return a.replace(/<\/?[b|em]>/gi,"")}
function Cb(a,b){return['href="',a,'" onmousedown="google.ac.r(event, this, \'',b,'\')" onclick="return google.ac.c(event)"'].join("")}function Eb(a,b,c){ba=k;if(a.which)ba=a.which==2;else if(a.button)ba=a.button==4;b.href=hb(c)}function Fb(a){if(ba){ib(a);return h}return k}
function ib(a){if(a){a.stopPropagation();a.cancelBubble=a.cancel=a.returnValue=h}}
function tb(){var a=F.insertRow(-1);a.w=1;a.onmousedown=ob;a=a.insertCell(0);a.className="gac_s";return a}function Pa(){Y();if(w&&$(y)&&L.value!=C.value)K.value=$(y).q;else{L.value="";K.value="f";if(N>=10)K.value="o"}}
function Xa(){if(s&&na!=s){if(n&&(s.indexOf(o)!=0||s.substr(s.length-1)==" ")){n=k;o=""}if(n)sb(Hb());else{N++;qb(va,"q",s,sb);C.focus()}}na=s;for(var a=100,b=1;b<=(N-2)/2;b++)a*=2;a+=50;oa=window.setTimeout(Xa,a)}
function Ib(){for(var a=["&gs_gbg="],b=4+Math.floor(Math.random()*32),c=0,d;c<b;++c){d=Math.random()<0.3?48+Math.floor(Math.random()*10):(Math.random()>0.5?65:97)+Math.floor(Math.random()*26);a.push(String.fromCharCode(d))}return a.join("")}function Hb(){var a=[];a[0]=s;for(var b=[],c=da[1],d=c.length,e=0,g,f;e<d;++e)if(f=c[e]){g=f[1];if(g==30){g=f[0]+s.substr(o.length);b.push([g,30,f[2]])}else ub(f)&&b.push([yb(f[0]),g,f[2],f[3]])}a[1]=b;Jb(2,a);Jb(3,a);Jb(4,a);return a}
function Jb(a,b){var c=da[a];if(c)b[a]=c}function ub(a){p.innerHTML=a[0];return!Kb(p).indexOf(s)}
function qb(a,b,c,d){W&&xa.removeChild(W);W=document.createElement("script");W.src=[la,"clients1.google.es",a,"&",b,"=",encodeURIComponent(c),ma?Ib():"","&cp="+R].join("");xa.appendChild(W);}function $a(a){if(C)C.value=r=a}function vb(a,b){a.appendChild(document.createTextNode(b))}
function ob(a){a.stopPropagation();return k}
var Va=function(a){var b=0,c=0;if(Nb(a)){b=a.selectionStart;c=a.selectionEnd}return b&&c&&b==c?b:0};var Nb=function(a){try{return typeof a.selectionStart=="number"}catch(b){return k}};
function Ma(){ea=h;fa=k;ga=h;ha=k;ia=h;q=ja=ka=k}function Na(a){if("a"in a)ea=a.a;if("f"in a)ja=a.f;if("l"in a)fa=a.l;if("n"in a)ga=a.n;if("o"in a)ha=a.o;if(X==2)ia=k;else if("p"in a)ia=a.p;if("s"in a)ka=a.s;if("sw"in a)q=a.sw}function Oa(){var a=[Ob];ea&&a.push(Pb);fa&&a.push(Qb);ga&&a.push(Rb);ha&&a.push(Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac);bc(a)}function bc(a){for(var b=0,c;c=a[b++];)ua[c.j]=c}
var Pb={j:8,b:"a",F:h,v:function(a,b,c){return c},m:function(a,b){return b[1]+Ua()},A:function(a,b){return a==b},g:function(a,b,c,d){b=d[0];var e=d[1]+Ua();c=d[2];var g=d[3];d=d[4];a.className="gac_f gac_p";var f=zb(b);e=Cb("http://"+f,e);a.innerHTML=['<table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td><table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td style="line-height:117%;vertical-align:bottom"><a class=q ',e,">",c,'</a><td class="gac_e gac_d gac_i">Enlace Patrocinado</table><tr><td class="gac_u gac_x gac_y" style="line-height:16px;padding-bottom:8px"><span class=gac_h',">",b,"</span>&nbsp; &nbsp;",g,d?" "+d:"","</table>"].join("")}},Xb={j:11,b:"b",B:h,m:function(a,b){return b[0]},g:function(a,b,c,d){b=d[0];c=d[1];var e=d[2],g=d[3],f=d[4],i=d[5],m=d[6];d=d[7];var t=b.match(/^([^&]*)/)[1];a.innerHTML=['<span class="gac_j gac_l"><a class=q ',Cb(t,b),"><b>",c,"</b> - ",e," (",g,")</a><br><b>",f,"</b> <span class=gac_y><span class=gac_",i>=0?"h":"r",">",i," (",m,"%)</span> ",d,' - </span><a href=/help/stock_disclaimer.html class="gac_d fl" onclick="google.ac.p(event);return true">Disclaimer</a></span>'].join("")}},
Yb={j:12,b:"c",m:function(a,b){return b[0]},g:function(a,b,c,d){b=d[0];c=d[1];d=d[2];for(var e="",g=d.length-1,f=0,i;f<g;f++){i=d[f];e+=[i[0],'<div class="gac_v">',i[1],"</div>"].join("")}i=d[g];e+=[i[0],"<br>",i[1]].join("");cc(1,a,c,b,"www.flightstats.com",e)}},Zb={j:15,b:"d",g:function(a,b,c,d){b=d[0];c=d[1];var e=d[2];d=d[3];a.innerHTML=["<b>",b,"</b> ",e," (",c,") in <b>",d,"</b>"].join("")}},$b={j:13,b:"e",m:function(a,b){return b[0]},g:function(a,b,c,d){b=d[0];c=d[1];d=d[2];cc(1,a,c,b,d)}},
Tb={j:14,b:"f",m:function(a,b){return b[0]},g:function(a,b,c,d){b=d[0];c=d[1];var e=d[2];d=d[3];cc(1,a,c,b,d,e)}},Ob={j:0,b:"g",v:function(a){return a.k},g:function(a,b,c){var d=c[0];a.innerHTML=d;c.k=Kb(a);if(ia&&Ca(b)=="p"){a.className="";a.innerHTML=["<table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td class=gac_c>",d,'<td class="gac_d gac_e fl"><a href=# onclick="return google.ac.dc(event,\'',b,"')\">Eliminar</a></table>"].join("");
}}},Ub={j:19,b:"h",g:function(a,b,c,d){b=d[0];d=d[1];a.innerHTML=["<b>",b," = ",d,"</b>"].join("")}},Sb={j:17,b:"i",m:function(a,b){return b[3]},g:function(a,b,c,d){b=d[0];c=d[1];var e=d[2];d=d[3];var g=d.match(/url=([^&]*)/)[1];a.innerHTML=['<span class="gac_j gac_l"><a ',Cb(g,d),">",b," &#151; ",c,": ",e,'</a><span class=gac_y style="line-height:16px"><br>According to <span class=gac_h>',
g,"</span></span></span>"].join("")}},ac={j:10,b:"j",g:function(a,b,c,d){b=d[0];c=d[1];var e=d[4];d=d[5];var g=function(f){var i=f[0],m=f[1],t=f[2],u=f[3];f=f[4];return['<td class=gac_w><img src="',i,'" alt="',m,'" title="',m,'"><td class="gac_c" style="line-height:112%;vertical-align:top">',f,"<br>",t,"&deg; | ",u,"&deg;"].join("")};a.innerHTML=["<b>Weather:</b> ",e,"&deg;",c," in ",b,"<br><table class=gac_t><tr>",g(d[0]),g(d[1]),g(d[2]),g(d[3]),"</table>"].join("")}},Vb={j:20,b:"k",g:function(a,
b,c,d){b=d[0];d=d[1];a.innerHTML=["<b>",b," = ",d,'</b> - <a href=/intl/en/help/currency_disclaimer.html class="gac_d fl" onclick="google.ac.p(event);return true">Disclaimer</a>'].join("")}},Wb={j:16,b:"l",v:function(a,b){return"define: "+b[0]},g:function(a,b,c,d){b=d[0];c=d[1];d=d[2];cc(1,a,"Web definitions for <b>"+b+"</b>","/search?q=define:"+b.replace(" ","+"),"www.google.com",[c," - <span class=gac_i>",d,"</span>"].join(""))}},Qb={j:30,b:"m",v:function(a){return a.k},g:function(a,b,c){b=c[0];
p.innerHTML=b;c.k=Kb(p);a.innerHTML=["<span class=gac_z>Did you mean: </span>",b].join("")}};function Kb(a){var b;b=a.textContent;return b}
var Rb={j:5,b:"n",v:function(a,b,c){return c},m:function(a,b){return b[0]},g:function(a,b,c,d){b=d[0];d=d[1];a.className="gac_c gac_n";a.style.lineHeight="117%";var e=c[0];c=e.replace(/HTTPS?:\/\//gi,"");e=zb(e);/^HTTPS?:\/\//i.test(e)||(e=(b.indexOf("/url?url=https:")>0?"https":"http")+"://"+e);b=Cb(e,b);a.innerHTML=["<span class=gac_x><a ",b,">",d,'</a><br><span class="gac_h gac_y"',">",c,"</span></span>"].join("");}};function cc(a,b,c,d,e,g,f){var i=d.indexOf("/url")?d:d.match(/url=([^&]*)/)[1];b.style.lineHeight="112%";b.innerHTML=["<a class=q ",Cb(i,d),">",c,'</a><span class="gac_y'+(a?" gac_x":"")+'">',g?g+"<br>":"",f?f+"<br>":"",e?"<span class=gac_h>"+e+"</span></span>":""].join("")}function Ua(){if(google.kEXPI)return"&expIds="+google.kEXPI;return""}l.c=Fb;l.d=rb;l.dc=pb;l.h=sb;l.i=La;l.p=ib;l.r=Eb;l.rd=ab;l.u=$a;google.bind(window,"resize",Sa);
google.dstr&&google.dstr.push&&google.dstr.push(Ia);})();
(function(){window.ManyBox={};var d,g,h=1,k=google.History.client(i),m=[];ManyBox.delayedRegister=function(a){m.push(a)};function n(a){for(var b in d)if(d[b].b&&a(d[b]))return}function o(a,b,c,e,f){this.b=a;this.k=b;this.C=e;this.p=f;this.r="/mbd?"+(b?"docid="+b:"")+"&resnum="+a.replace(/[^0-9]/,"")+"&mbtype="+e+"&usg="+c+"&hl="+(google.kHL||"");this.e={};this.n="";g[a]={s:0,F:this.e,k:this.k,j:0};this.o=0}o.prototype.append=function(a){this.n+="&"+a.join("&")};
function p(a,b){a.h.style.paddingTop=b+"px";a.h.style.display=a.h.innerHTML?"":"none";if(b>a.o)a.o=b;a.i.style.fontSize=b+"px";a.i.style.fontSize=null}
function r(a){if(!a.B){a.B=1;a.d=document.getElementById("mbb"+a.b);if(a.d){a.l=0;a.a=document.getElementById("mbl"+a.b);if(a.a){a.i=a.a.getElementsByTagName("DIV")[0];a.q=a.a.getElementsByTagName("A")[0];a.A=a.q.innerHTML;a.p=a.p||a.A;a.i.title="Haz clic para obtener más información";a.a.G=function(b,c){var e=google.style.getPageOffsetStart(a.a),f=google.style.getPageOffsetTop(a.a);return b>e-5&&b<e+google.style.getWidth(a.a)+5&&c>f-5&&c<f+google.style.getHeight(a.a)+5};a.h=document.getElementById("mbf"+a.b);p(a,0);a.a.onmousedown=
s(a);a.a.onclick=t(a);a.a.go=function(){a.a.onmousedown();a.a.onclick()}}else delete d[a.b]}else delete d[a.b]}}function u(a){google.log("manybox",[a.l?"close":"open","&id=",a.b,"&docid=",a.k,"&mbtype=",a.C,a.n].join(""))}
function s(a){return function(){if(g[a.b].j)a.J++<3&&u(a);else{if(a.e.m)u(a);else{var b=google.xhr();if(b){b.open("GET",a.r+a.n+"&zx="+google.time());a.u=0;b.onreadystatechange=function(){if(b.readyState==4){var c=0;if(b.status==200)try{eval(b.responseText);c=1}catch(e){}if(!c&&!a.D){g[a.b].j=0;a.D=1;a.r+="&cad=retry";a.a.onmousedown()}else{a.v&&v(a);a.u=0}}};a.u=1;b.send(null)}}g[a.b].j=a.J=1}}}function t(a){return function(){g[a.b].j||a.a.onmousedown();(a.v=a.u)||v(a)}}
function w(a){if(!a.e.m){a.e.m="\x3cfont color\x3dred\x3eError:\x3c/font\x3e El servidor no pudo llevar a cabo tu solicitud. Vuelve a intentarlo transcurridos 30 segundos.";a.H=a.a.onclick;a.a.onclick=function(){h=0;v(a);h=1;a.c.parentNode.removeChild(a.c);g[a.b].j=a.e.m=a.w=0;a.a.onclick=a.H}}if(!a.w){a.w=1;var b=document.getElementById("res");a.I=b&&google.style.getPageOffsetStart(a.d)>google.style.getPageOffsetStart(b)+google.style.getWidth(b);a.c=document.createElement("div");p(a,0);a.c.style.position="absolute";a.c.style.paddingTop=a.c.style.paddingBottom="6px";a.c.style.display="none";a.c.className="med";b=document.createElement("div");
a.c.appendChild(b);b.className="std";b.innerHTML=a.e.m;a.h.parentNode.insertBefore(a.c,a.h)}}function i(a){h=0;ManyBox.init();n(function(b){if(b.k==a[b.b].k){b.e=a[b.b].F;a[b.b].s!=b.l&&v(b)}else a[b.b].j=0});g=a;h=1;google.History.save(k,g)}ManyBox.create=function(a,b,c,e,f){return new o(a,b,c,e,f)};ManyBox.register=function(a,b,c,e,f){return d[a]=ManyBox.create(a,b,c,e,f)};
google.listen(document,"click",function(a){a=a||window.event;for(var b=a.target||a.srcElement;b.parentNode;){if(b.tagName=="A"||b.onclick)return;b=b.parentNode}n(function(c){if(c.a.G(a.clientX,a.clientY)){c.a.go();return 1}})});function x(){d={};g={};m=[];history.navigationMode=history.navigationMode&&"fast"}x();ManyBox.init=function(){for(var a=0;a<m.length;a++)try{m[a].func()}catch(b){delete d[m[a].id]}m=[];n(r)};
function y(a,b){a.c.style.clip="rect(0px,"+(a.d.width||"34em")+","+(b||1)+"px,0px)"}o.prototype.insert=function(a){this.e.m=a};function z(a){a.g=document.getElementById("mbcb"+a.b);var b=a.g&&a.g.getAttribute("mbopen");if(b){eval(b);a.onopen(a.g)}}function A(a){a.c.style.display="none";a.i.style.backgroundPosition="-153px -70px";a.q.innerHTML=a.A;a.l=g[a.b].s=0;google.History.save(k,g)}
function B(a,b,c,e,f){var l=c>0?150:75,j=google.time()-f;l=j<l&&h?j/l*c:e>1?c-10:c;j=Math.max(a.t,b+l);var q=j-a.t;y(a,q);a.d.style.height=j<0?0:q?j+"px":"";p(a,Math.max(0,q-5));google.rhs();Math.abs(l)<Math.abs(c)?window.setTimeout(function(){B(a,b,c,e-1,f)},30):window.setTimeout(function(){c<0?A(a):z(a);if(!google.browser.engine.IE&&a.I)a.c.style.width="100px";a.c.style.position=a.d.style.height="";p(a,0);google.rhs();a.d.z=0},0)}
function v(a){a.v=0;if(!a.d.z){a.d.z=1;var b;if(a.l){if(b=a.g&&a.g.getAttribute("mbclose")){eval(b);a.onclose(a.g)}b=a.t-google.style.getHeight(a.d);a.h.style.display="none";p(a,a.o);a.c.style.position="absolute"}else{a.t=google.style.getHeight(a.d);w(a);p(a,0);a.o=0;n(function(c){c.i.title=""});a.i.style.backgroundPosition="-153px -84px";a.q.innerHTML=a.p;y(a,1);a.c.style.position="absolute";a.c.style.display="";a.l=g[a.b].s=1;google.History.save(k,g);b=a.c.offsetHeight}B(a,google.style.getHeight(a.d),
b,google.browser.product.SAFARI?2:1,google.time())}}google.dstr&&google.dstr.push(x);})();
(function (){var j,k;
function o(){j=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(j);k=j.sheet;}
google.addCSSRule=function(a,b){j||o();c=a+"{"+b+"}";k.insertRule(c,k.cssRules.length);};google.acrs=function(a){a=a.split(/{|}/);for(var b=1;b<a.length;b+=2)google.addCSSRule(a[b-1],a[b])};google.Toolbelt.ascrs=function(){};
var p,q;function r(){google.nav(document.getElementById("tbpi").href)}function t(a){google.srp.updateLinksWithParam("tbo",a?"1":"",google.srp.isSerpLink,google.srp.isSerpForm)}
function u(){mbtb1.insert=function(b){try{v(eval(b))}catch(c){r()}};var a=google.xhr();if(a){a.open("GET",[google.base_href.indexOf("/images?")==0?google.base_href.replace(/^\/images\?/,"/mbd?"):google.base_href.replace(/^\/search\?/,"/mbd?"),"&mbtype=29&resnum=1&tbo=1",mbtb1.tbs?"&tbs="+mbtb1.tbs:"","&docid=",mbtb1.docid,"&usg=",mbtb1.usg,"&zx=",google.time()].join(""),true);a.onreadystatechange=function(){if(a.readyState==4)if(a.status==200)try{eval(a.responseText)}catch(b){r()}else r()};a.send(null)}}
function v(a){for(var b=0,c=0,d,e;(d=a[b])&&(e=q[c]);b++,c++)if(google.Toolbelt.pti[c])e.id!=d[0]&&b--;else{if(d[2]){e.className="tbos";google.listen(e,"click",google.Toolbelt.tbosClk)}else e.className="tbou";e.id=d[0];e.innerHTML=d[1]}}function x(a){for(var b=0,c;c=google.Toolbelt.pbt[b++];)if(c[0]==a)return true;return false}
google.Toolbelt.initializeToolElements=function(){p=[];q=[];var a=document.getElementById("tbd");if(a){for(var b=a.getElementsByTagName("ul"),c=0,d;d=b[c++];){p.push(d);d=d.getElementsByTagName("li");for(var e=0,f;f=d[e++];)q.push(f)}}};
function y(){var a=document.getElementById("tbd");if(!a.getAttribute("data-loaded")){a.setAttribute("data-loaded",1);var b=[],c=0;var d='<li style="opacity:0">';for(var e=0,f=google.Toolbelt.atg.length;e<f;++e){var h=google.Toolbelt.atg[e],g=google.style.hasClass(p[e],"tbpd");b.push('<li><ul class="tbt'+(g?" tbpd":"")+'">');for(var n;(n=
google.Toolbelt.pbt[c])&&n[0]==e;c++){for(g=0;g++<n[1];)b.push(d);b.push('<li class="'+q[c].className+'" id='+q[c].id+">"+q[c].innerHTML)}for(g=0;g++<h;)b.push(d);b.push("</ul>")}a.innerHTML=b.join("");google.Toolbelt.initializeToolElements();u()}}
function z(a){for(var b=[],c=[],d=a?0:1,e=a?1:0,f=null,h=0,g;g=p[h];h++){google.style.hasClass(g,"tbpd")||b.push([g,"marginBottom",d*8,e*8]);if(x(h))f=g;}
google.style.hasClass(f,"tbpd")&&b.push([f,"marginBottom",d*8,e*8]);for(h=0;f=q[h];h++)if(!google.Toolbelt.pti[h]){b.push([f,"height",d*1.2,e*1.2,0,"em"]);b.push([f,"paddingBottom",d*3,e*3]);c.push([f,"opacity",d,e,0,""]);f.style.overflow="hidden";}d=a?b:c;var C=a?c:b;google.fx.animate(300,d,function(){document.body.className=
document.body.className.replace(/\btbo\b/,"")+(a?" tbo":"");google.fx.animate(200,C,function(){var s=a?"":"none";for(m=0;i=q[m];m++){if(a){i.style.height=
"";i.style.overflow="visible";i.style.opacity="";}}})})}google.Toolbelt.togglePromotedTools=function(){var a=!google.style.hasClass(document.body,"tbo");a&&y();t(a);z(a);google.log("toolbelt",(a?"0":"1")+"&ei="+google.kEI);return false};
google.rein.push(google.Toolbelt.initializeToolElements);function A(a){for(;a&&!google.hasClass(a,"tbt");)a=a.parentNode;return a}
google.Toolbelt.ctlClk=function(a,b,c){a=a||"cdr_opt";if(a=="cdr_opt"){c&&c.stopPropagation();}google.Toolbelt.maybeLoadCal&&google.Toolbelt.maybeLoadCal();b=b||"cdr_min";if(a=document.getElementById(a)){a.className="tbots";if(a=A(a)){c=0;for(var d;d=a.childNodes[c++];)if(d.className=="tbos")d.className="tbotu";(b=document.getElementById(b))&&
b.focus()}}return false};google.Toolbelt.cdrClk=google.Toolbelt.ctlClk;function B(a){return a.replace(/_/g,"_1").replace(/,/g,"_2").replace(/:/g,"_3")}google.Toolbelt.cdrSbt=function(){return D("ctbs",{cdr_min:"cd_min",cdr_max:"cd_max"})};google.Toolbelt.clSbt=function(){return D("ltbs",{l_in:"cl_loc"})};google.Toolbelt.prcSbt=function(){D("prcbs",{prc_min:"pr_min",prc_max:"pr_max"});var a=document.getElementById("prc_frm");if(a){var b=document.getElementById("tsf");if(b)a.elements.q.value=b.elements.q.value}};
function D(a,b){var c=document.getElementById(a);if(c)for(var d in b){var e=B(document.getElementById(d).value),f=new RegExp("("+b[d]+":)([^,]*)");c.value=c.value.replace(f,"$1"+e)}return true}google.Toolbelt.tbosClk=function(a){a=a||window.event;if((a=a.target||a.srcElement)&&a.className=="tbotu"){a.className="tbos";if(a=A(a))for(var b=0,c;c=a.childNodes[b++];)if(c.className=="tbots")c.className="tbou"}};})();
if(!window.gbar||!gbar.close){window.gbar={};(function(){var e=window.gbar,g,k;function l(a){var b=window.encodeURIComponent&&(document.forms[0].q||"").value;if(b)a.href=a.href.replace(/([?&])q=[^&]*|$/,function(c,d){return(d||"&")+"q="+encodeURIComponent(b)})}e.qs=l;function m(a,b,c,d,j,h){var f=document.getElementById(a),i=f.style;if(f){i.left=d?"auto":b+"px";i.right=d?b+"px":"auto";i.top=c+"px";i.visibility=k?"hidden":"visible";if(j&&h){i.width=j+"px";i.height=h+"px"}else{m(g,b,c,d,f.offsetWidth,f.offsetHeight);k=k?"":a}}}e.tg=function(a){a=a||window.event;var b=a.target||a.srcElement;a.cancelBubble=true;if(g!=null)n(b);else{a=document.createElement(Array.every||window.createPopup?"iframe":"div");a.frameBorder="0";a.src="#";g=b.parentNode.appendChild(a).id="gbs";document.onclick=e.close;n(b);e.alld&&e.alld(function(){var c=document.getElementById("gbli");if(c){var d=c.parentNode;d.removeChild(c);o(d)}})}};function p(a){var b,c=document.defaultView;if(c&&c.getComputedStyle){if(a=c.getComputedStyle(a,""))b=a.direction}else b=a.currentStyle?a.currentStyle.direction:a.style.direction;return b=="rtl"}function n(a){var b=0;if(a.className!="gb3")a=a.parentNode;var c=a.getAttribute("aria-owns")||"gbi",d=a.offsetWidth,j=a.offsetTop>20?46:24,h=false;do b+=a.offsetLeft||0;while(a=a.offsetParent);a=(document.documentElement.clientWidth||document.body.clientWidth)-b-d;d=p(document.body);if(c=="gbi"){var f=document.getElementById("gbi");e.alli&&e.alli(f);o(f);if(d){b=a;h=true}}else if(!d){b=a;h=true}k!=c&&e.close();m(c,b,j,h)}e.close=function(){k&&m(k,0,0)};function q(a,b){var c=a.firstChild?a.firstChild.className:"gb2";a.insertBefore(b,a.firstChild).className=c}function o(a){for(var b,c=window.navExtra;c&&(b=c.pop());)q(a,b)}})();;};
if(!window.google)window.google={};window.google.crm={};window.google.cri=0;
window.clk=function(e,f,g,k,l,b,m){if(document.images){var a=encodeURIComponent||escape,c=new Image,h=window.google.cri++;window.google.crm[h]=c;c.onerror=c.onload=c.onabort=function(){delete window.google.crm[h]};var d,i,j;if(google.v6){d=
google.v6.src;i=google.v6.complete||google.v6s?2:1;j=(new Date).getTime()-google.v6t;delete google.v6}if(b&&b.substring(0,6)!="&sig2=")b="&sig2="+b;c.src=["/url?sa=T","&source="+google.sn,"&cd=",a(l),google.j&&google.j.pf?"&sqi=2":"","&ved=",a(m),e?"&url="+a(e.replace(/#.*/,"")).replace(/\+/g,
"%2B"):"","&ei=",google.kEI,d?"&v6u="+a(d)+"&v6s="+i+"&v6t="+j:"",b].join("")}return true};
window.rwt=function(a,f,g,k,l,h,c,m){try{if(a===window)for(a=window.event.srcElement;a;){if(a.href)break;a=a.parentNode}var b=encodeURIComponent||escape,d;d=a.getAttribute("href");var e,
i,j;if(google.v6){e=google.v6.src;i=google.v6.complete||google.v6s?2:1;j=(new Date).getTime()-google.v6t;delete google.v6}if(c&&c.substring(0,6)!="&sig2=")c="&sig2="+c;var n=["/url?sa=t","&source="+google.sn,"&cd=",b(l),google.j&&google.j.pf?"&sqi=2":"","&ved=",b(m),"&url=",b(d).replace(/\+/g,
"%2B"),"&ei=",google.kEI,e?"&v6u="+b(e)+"&v6s="+i+"&v6t="+j:"",h?"&usg="+h:"",c].join("");a.href=n;a.onmousedown=""}catch(o){}return true};
(function(){var b,f=function(){document.getElementById("ss-box").style.visibility="hidden";document.body.removeEventListener?document.body.removeEventListener("click",google.safeSearchBar.toggle,false):document.body.detachEvent("onclick",google.safeSearchBar.toggle);if(b)b.style.visibility="hidden"},g=function(){var a=document.getElementById("ss-box"),d=document.getElementById("ss-status");if(!b){b=document.createElement(Array.every||window.createPopup?"iframe":"div");b.frameBorder="0";b.src="#";a.parentNode.appendChild(b).id=
"ss-barframe";var c=a.offsetWidth-2;document.getElementById("ss-off").style.width=c+"px";document.getElementById("ss-moderate").style.width=c+"px";document.getElementById("ss-strict").style.width=c+"px"}c=0;do c+=d.offsetLeft;while(d=d.offsetParent);a.style.visibility="visible";b.style.visibility="visible";b.style.width=a.offsetWidth+"px";b.style.height=a.offsetHeight+"px";b.style.position="absolute";b.style.top=a.offsetTop+"px";google.bind(document.body,"click",google.safeSearchBar.toggle)},h=function(a,
d,c){return[a.replace(new RegExp("([?&])"+d+"=([^&]*)&?","i"),"$1").replace(/&$/i,""),"&",d,"=",c].join("")};google.safeSearchBar={toggle:function(a){if(!google.nossbar){a=a||window.event;a.cancelBubble=true;a.stopPropagation&&a.stopPropagation();a=document.getElementById("ss-box");a.style.visibility=="visible"?f():g()}},updateLinkUrl:function(a){for(var d=["ss-off","ss-moderate","ss-strict"],c=0,e;e=d[c++];)if(e=document.getElementById(e))e.href=h(e.href,"prev",encodeURIComponent(a))}};})();
(function(){var f=true,g=false;window.google.rt={};var h,i,j,k,l,m,o,p,q,r,s,t,u,v,w,x,y;function aa(){h=30;i=[];k=j=g;l="";o=0;p=g;q=(new Date).getTime();r=100;s=0;t=g;y=[]}
google.rt.init=function(a,c,b){aa();if(m=document.getElementById(a)){if(b)if(b.maxResults)r=b.maxResults;document.onmousemove=function(){p=f};document.onkeydown=function(){p=f};c&&z(c);s+=m.getElementsByTagName("li").length;i.length==0&&window.setTimeout(A,3E3);ba();ca(m,y);da(m,y);B(A,h);if(ea("sbu","sbd","sbb",a)){C.push(function(){k=f});D.push(function(){k=g});E(0,f)}fa(ga,3E3,6E3)}};
google.rt.pause=function(){ha();F();var a=document.getElementById("rth");a=a.getElementsByTagName("span");G(a[0]);H(a[1]);x=(new Date).getTime()};google.rt.resume=function(){var a=((new Date).getTime()-x)/1E3;if(a>10)i=[];A();B(A,h);fa(ga,2E3,6E3);a=document.getElementById("rth");a=a.getElementsByTagName("span");G(a[1]);H(a[0])};function G(a){a.style.display="none"}function H(a){a.style.display=""}
function B(a,c){var b=c;if(o){b=Math.pow(2,o)*5;b=(Math.random()+0.5)*b;b=Math.min(7200,b)}w=window.setTimeout(function(){a();B(a,c)},b*1E3)}function ha(){window.clearTimeout(w)}function fa(a,c,b){u=window.setTimeout(function(){a();v=window.setInterval(a,b)},c)}function F(){window.clearTimeout(u);window.clearInterval(v)}
function ga(){if(!i.length||k){if(t){F();var a=document.getElementById("rth");a=a.getElementsByTagName("span");if(a.length>2){G(a[0]);G(a[1]);H(a[2])}}}else{var c=i.shift();a=c.e;var b=a.getElementsByTagName("li")[0];m.insertBefore(a,m.firstChild);c.updateDate();google.History.save(ia,{r:m.innerHTML,u:l,n:s,s:y,t:I()});var d=-google.getComputedStyle(b,"height")-google.getComputedStyle(b,"margin-bottom");c=m.scrollTop;if(c<20){E(c);a=[[a,"marginTop",d,0,google.fx.easeInAndOut]];google.fx.animate(1200,a)}else E(c-d)}}function z(a){if(a.results){var c=a.results.length;s+=c;c=c;for(var b;b=a.results[--c];)i.push(ja(b))}if(a.nextRequest)l=a.nextRequest;if(a.pollSeconds)h=a.pollSeconds}window.mbrt0=window.mb0rt={insert:function(a){a=eval("("+a+")");z(a)}};
function A(){if(p){p=g;q=(new Date).getTime()}else if((new Date).getTime()-q>24E4)return;t=s+5>r;if(!(j||t||!l)){var a=google.xhr();a.open("GET",l);a.onreadystatechange=function(){if(a.readyState==4){if(a.status==200){eval(a.responseText);o=0}else o++;j=g}};j=f;a.send(null)}}function ja(a){var c=document.createElement("div");c.innerHTML=a.html;return{e:c,updateDate:ka(c,y)}}var ia=google.History.client(function(a){m.innerHTML=a.r;l=a.u;s=a.n;y=a.s;J(m,y,a.t);E(0,f);i=[];A()});
google.dstr.push(function(){F();ha()});var K,L,M,N,O,P,Q,C,D,R,S,T=g;function U(a){var c=google.getComputedStyle(a,"height");return c}function V(a){a=a.offsetTop;a-=N.offsetTop;return a}
function W(a){if(a)for(var c=0,b;b=C[c++];)b();else if(Q)for(c=0;b=D[c++];)b();Q=a}function X(a){var c=la(a);if(c){var b=V(c);a||(b+=U(c)-S);ma(b,f,300,function(){na(a)})}}function ma(a,c,b,d){var e=N.scrollHeight-S;e=e==0?0:oa(a*(R-Math.max(S/N.scrollHeight*R,20))/e);e=[[M,"marginTop",google.getComputedStyle(M,"margin-top"),e,google.fx.easeInAndOut]];if(c)e.push([N,"scrollTop",N.scrollTop,a,google.fx.easeInAndOut,""]);else N.scrollTop=a;google.fx.animate(b,e,d)}
function na(a){setTimeout(function(){Q&&X(a)},200)}function la(a){var c=N.childNodes;if(a)for(a=c.length-1;a>=0;--a){var b=c[a],d=V(b);if(b.nodeType==1&&d<N.scrollTop)return b}else for(a=0;b=c[a++];){d=V(b);if(b.nodeType==1&&d+U(b)>N.scrollTop+S)return b}}function Y(a){var c=a.clientY-O;c=oa(google.getComputedStyle(M,"margin-top")+c);M.style.marginTop=c+"px";N.scrollTop=c*(N.scrollHeight-S)/(R-U(M));O=a.clientY}function oa(a){return Math.max(0,Math.min(R-U(M),a))}
function E(a,c){if(T){var b=U(M),d=Math.max(S/N.scrollHeight*R,20),e=document.getElementById("sbbb");b=[[M,"height",b,d],[e,"marginTop",b-7,d-7]];if(!P){e=d=0;for(var n;n=N.childNodes[e++];)if(n.nodeType==1)d+=U(n);if(d>S){b.push([document.getElementById("sb"),"opacity",0,1,google.fx.linear,""]);P=f}}d=c?0:1200;ma(a,g,d);google.fx.animate(d,b,function(){if(P)M.style.position="absolute"})}}
function Z(a,c){if(a.parentNode==M)a=M;var b=70*(c?1:-1);pa(a,b);for(var d=0,e;e=a.childNodes[d++];)e.nodeType==1&&pa(e,b)}function pa(a,c){var b=a.style.backgroundPosition.match(/^-?\d+/),d=a.style.backgroundPosition.match(/\s+.*$/);a.style.backgroundPosition=parseInt(b,10)+c+"px "+(d?d:"")}
function ea(a,c,b,d){K=document.getElementById(a);L=document.getElementById(c);M=document.getElementById(b);N=document.getElementById(d);if(!(K&&L&&M&&N))return T=g;Q=P=g;C=[];D=[];R=google.getComputedStyle(document.getElementById("sbc"),"height")-1;S=google.getComputedStyle(N,"height");a=[K,L,M];for(c=0;b=a[c++];){google.bind(b,"mouseover",function(e){Z(e.target)});google.bind(b,"mouseout",function(e){Z(e.target,f)});b.onmousedown=function(){return g};
}google.bind(K,"mousedown",function(){W(f);X(f)});google.bind(L,"mousedown",function(){W(f);X()});google.bind(M,"mousedown",function(e){W(f);O=e.clientY;google.bind(document,"mousemove",Y)});return T=f}
google.bind(document,"mouseup",function(){document.removeEventListener("mousemove",Y,g);W(g)});google.dstr.push(function(){C=D=[];T=g});window.google.rt||(window.google.rt={});var qa=-1;google.rt.timestampToString=null;
function ra(a,c){for(var b=a.getElementsByTagName("div"),d=0,e;e=b[d++];)if(e.className=="rtdelta"){b=parseInt(e.innerHTML,10);return c-b}return g}function I(){return Math.round((new Date).getTime()/1E3)}
function sa(a,c){var b=c-a;if(b<86400)if(b<45)return"hace segundos";else if(b<105)return"Hace 1 minuto.";else if(b<3345){b=Math.floor(b/60)+(b%60>=45?1:0);return"hace 1 minutos".replace("1",b+"")}else if(b<6600)return"hace 1 hora";else{b=Math.floor(b/3600)+(b%3600>=3E3?1:0);return"hace 1 horas".replace("1",b+"")}return g}function ta(a,c,b,d){if(c)if(c=d(c,b))a.innerHTML=c}
function $(a){var c=[];a=a.getElementsByTagName("span");for(var b=0,d;d=a[b++];)d.className.match("rtd")&&c.push(d);return c}function ua(a){a=$(a);if(a.length>0)return a[0];return g}function J(a,c,b){a=$(a);b=b||I();for(var d=0,e;e=a[d];d++)ta(e,c[d],b,google.rt.timestampToString)}function ka(a,c,b){var d=b||I();return function(){var e=ua(a);if(e){var n=ra(e,d);if(n){ta(e,n,I(),google.rt.timestampToString);c.unshift(n)}}}}
function ca(a,c,b){a=$(a);b=b||I();for(var d=0,e;e=a[d++];)(e=ra(e,b))&&c.push(e)}function da(a,c){qa=window.setInterval(function(){J(a,c)},6E4);google.dstr.push(function(){window.clearInterval(qa)})}function ba(){google.rt.timestampToString=sa}google.rt.replayCallbacks=[];google.rt.pushReplayCallback=function(a){google.rt.replayCallbacks.push(a)};function va(){google.rt.timestampToString=function(a){return google.rt.formatTime(a,"FullDate")}}
google.rt.replayinit=function(a){m=document.getElementById(a);y=[];va();if(m){google.rt.pushReplayCallback(function(){ca(m,y,null);J(m,y)});google.History.save(ia,{r:m.innerHTML,s:y,t:I()})}};})();
(function(){var e=false;function h(a){google.srp.updateLinksWithParam("prmdo",a?"1":"",google.srp.isSerpLink,google.srp.isSerpForm)}function i(a,c,b){return[[c,"height",a?b:0,a?0:b],[c,"opacity",a?1:0,a?0:1,null,""]]}function j(a){if(!a)return null;var c=a.offsetHeight,b=google.style.getComputedStyle(a,"overflow",1);a.style.overflow="hidden";return{height:c,overflow:b}}
function l(a,c,b){if(c)a.style.height=b.height+"px";else a.style.removeAttribute&&a.style.removeAttribute("filter");a.style.overflow=b.overflow}
google.srp.toggleModes=function(){if(!e){e=true;var a=document.getElementById("ms"),c=document.getElementById("hidden_modes"),b=document.getElementById("hmp"),d=google.style.hasClass(a,"open");a.className="open";var k=j(c),f=j(b),g=i(d,c,k.height);if(f)g=g.concat(i(d,b,f.height));h(!d);google.fx.animate(227,g,function(){if(d)a.className="";l(c,d,k);b&&l(b,d,f);e=false})}};})();
(function(){google.tbpr={};
var d={},g=/\bl\b/,h=function(a){return g.test(a.className)},j=function(){for(var a=document.getElementsByTagName("h3"),b=0,c;c=a[b++];)if(c.className=="tbpr"){var e=Number(c.id.substr(5));d[e]=c;i(c,e)}},i=function(a,b){for(;a&&a.nodeName!="LI";)a=a.parentNode;if(a)for(var c=a.getElementsByTagName("a"),e=0,f;f=c[e++];)if(h(f)){f.resultIndex=b;return}},k=function(){for(var a in d)d[a].style.display="none"},l=function(a){if(d[a])d[a].style.display="block"},m=function(a){var b="";k();if(a.lastClicked>=
0){l(a.lastClicked);b="tbpr:idx="+a.lastClicked}return b},n=function(a,b){b.lastClicked=a.resultIndex||-1};google.tbpr.init=function(){j();google.event.back.init();google.event.back.register(h,n,m,"tbpr")};})();
(function(){if(!google.nolujs){google.LU={};var c,d=[],e,h,k,l,m,n,o,p,q,r;google.LU.featureMap=function(a){if((d=a)&&d.length>0)s();else d=[]};var t=function(a){for(var b=0,g;b<d.length;++b)if(g=d[b].features)for(var f=0,i;i=g[f];++f)if(!a(i))return},u=function(){q=e.offsetWidth;r=e.offsetHeight},s=function(){google.listen(e,"mousemove",v);var a=d[0].rectangle;if(a&&a.length==4){n=a[2]-a[0];o=a[3]-a[1]}p=e.style.background.indexOf("center")!=-1||e.style.background.indexOf("50% 50%")!=-1;google.log("lu_featuremap",
google.time()-c+"")},w=function(a){var b=o/r;a={x:a.x*b,y:a.y*b};if(p)a.x+=(n-q*b)/2;return a},x=0,v=function(a){var b=google.time();if(!(b-x<100)){x=b;u();a={x:(a||window.event).clientX+document.body.scrollLeft+document.documentElement.scrollLeft-google.style.getPageOffsetLeft(e),y:(a||window.event).clientY+document.body.scrollTop+document.documentElement.scrollTop-google.style.getPageOffsetTop(e)};a=w(a);a=y(a.x,a.y);h.href=l;if(a){a=a.id;h.style.cursor="pointer";if(!m&&a!="0")h.href+="&iwloc="+
a}else h.style.cursor="default"}},y=function(a,b){if(d.length==0)return null;var g=null;t(function(f){var i=a-f.a[0],j=b-f.a[1];if(i>=f.bb[0]&&j>=f.bb[1]&&i<=f.bb[2]&&j<=f.bb[3]){g=f;return false}return true});return g};google.LU.init=function(a){if(e=document.getElementById("lu_map")){for(h=e;h&&h.tagName!="A";)h=h.parentNode;for(k=h;k&&(k.tagName!="LI"||google.style.hasClass("g"));)k=k.parentNode;if(h&&k){l=h.href;m=l.indexOf("&iwloc=")!=-1||l.indexOf("&cid=0,0,")!=-1;var b;if(e.tagName=="IMG")b=
e.src;else{b=/url\(([\'\"]?)(.*)\1\)/.exec(e.style.background);if(!b||b.size<3)return;b=b[2]}var g=/\/vt\/data=[^,]+,[^,]+$/;if(g.test(b)){g=b.indexOf("data=");var f=b.indexOf(","),i=b.substring(0,g+5)+a+b.substr(f)+"&callback=google.LU.featureMap";k.fetchOnce=true;k.fetch=function(){if(k.fetchOnce){k.fetchOnce=false;c=google.time();google.unlisten(k,"mouseover",k.fetch);var j=document.createElement("SCRIPT");j.src=i;google.append(j)}};google.listen(k,"mouseover",k.fetch)}}}};var z=function(){e&&
google.unlisten(e,"mousemove",v);d.length=0};google.dstr&&google.dstr.push(z)};})();
if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.y.x=google.x;google.x=function(d,c){c&&c.apply(d);return false};google.y.first=[];
(function (){if(window.google){window.google.a={};window.google.c=1;var j=function(a,b,e){b=a.t[b];a=a.t.start;if(b&&(a||e)){if(e!=undefined)a=e;return b>a?b-a:a-b}},k=function(a,b,e){var d="";if(window.google.pt){d+="&srt="+window.google.pt;delete window.google.pt}var c=document.getElementById("csi");if(c){var f;if(window.google._bfr!=undefined)f=window.google._bfr;else{f=c.value;window.google._bfr=f;c.value=1}if(f)return""}if(c=window.chrome)if(c=c.loadTimes){if(c().wasFetchedViaSpdy)d+="&p=s";if(c().wasNpnNegotiated)d+=
"&npn=1";if(c().wasAlternateProtocolAvailable)d+="&apa=1"}if(a.b)d+="&"+a.b;if(window.parent!=window)d+="&wif=1";c=a.t;f=c.start;var g=[];for(var h in c)h!="start"&&f&&g.push(h+"."+j(a,h));delete c.start;if(b)for(var i in b)d+="&"+i+"="+b[i];return a=[e?e:"/csi","?v=3","&s="+(window.google.sn||"GWS")+"&action=",a.name,"",d,"&rt=",g.join(",")].join("")};window.google.report=function(a,b,e){a=k(a,b,e);b=new Image;var d=window.google.c++;window.google.a[d]=b;b.onload=b.onerror=function(){delete window.google.a[d]};
b.src=a;b=null;return a}};function l(){function a(c){try{var f=window.external[c];if(f!=undefined){google.kCSI[c]=f;return true}}catch(g){}return false}for(var b=["ist_rc","ist_rn","ist_nr","ist_cdts","ist_dp","ist_rrx","ist_rxr","ist_rs","ist_sr"],e=0,d;d=b[e++];)if(a(d)===false)break}
if(google.timers&&google.timers.load.t){if(!google.nocsixjs)google.timers.load.t.xjsee=google.time();window.setTimeout(function(){if(google.timers.load.t){google.timers.load.t.xjs=google.time();l();google.timers.load.t.ol&&google.report(google.timers.load,google.kCSI)}},0)};})();
